version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: translation_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: translation_db
    ports:
      # host port: container port
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
